// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWrHeKXpxtTLQgUH1VuXvi7JphhGPKB24',
    appId: '1:31170742929:web:a2e7c40dbdc715a0424d30',
    messagingSenderId: '31170742929',
    projectId: 'digitalads-84cb8',
    authDomain: 'digitalads-84cb8.firebaseapp.com',
    storageBucket: 'digitalads-84cb8.firebasestorage.app',
    measurementId: 'G-8XCX083030',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU8qxgPOquB9UVXJd7VLAVuHu8MAV8B3I',
    appId: '1:31170742929:android:80c5a8a4fbd77ea4424d30',
    messagingSenderId: '31170742929',
    projectId: 'digitalads-84cb8',
    storageBucket: 'digitalads-84cb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArfuRZHkvGwoku0e5Wtauh2-MWWq2kjE8',
    appId: '1:31170742929:ios:c2afacbfedf0b50e424d30',
    messagingSenderId: '31170742929',
    projectId: 'digitalads-84cb8',
    storageBucket: 'digitalads-84cb8.firebasestorage.app',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArfuRZHkvGwoku0e5Wtauh2-MWWq2kjE8',
    appId: '1:31170742929:ios:c2afacbfedf0b50e424d30',
    messagingSenderId: '31170742929',
    projectId: 'digitalads-84cb8',
    storageBucket: 'digitalads-84cb8.firebasestorage.app',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWrHeKXpxtTLQgUH1VuXvi7JphhGPKB24',
    appId: '1:31170742929:web:65b75ee83308a10f424d30',
    messagingSenderId: '31170742929',
    projectId: 'digitalads-84cb8',
    authDomain: 'digitalads-84cb8.firebaseapp.com',
    storageBucket: 'digitalads-84cb8.firebasestorage.app',
    measurementId: 'G-X3K03HC775',
  );
}
